# Generated by Django 3.2.3 on 2021-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('first_price', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('featured', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
